language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install flake8>=3.8.2 flake8-bugbear>=20.1.4 pep8-naming>=0.10.0
  - pip install black>=19.10b0
script:
  - black --check .
  - flake8
deploy:
  provider: pypi
  username: newAM
  password:
    secure: V/dvXAggHFs0NUD8DTIgJfLasWbBeT5qT839ToibboxpVReQywgiUpV9Idtq7rGskUvJD5scE9E1H69KQK8y/0vGG/kneAt8cuuj3GYbRBU9KVEFdnAYoyJ4r8mBhuAYDX0UU7YFzNR1cwwObc0JbbKip6/RLqd/43xJ9RcbvqCZb2aIV8kO8lUMBHHz1jMRVrujhB0+84+2AJdx/KZldMhy2GhKG5FGMGKGVswoBwMqr9ohzJa9NYe6Zfn4NC7IDv367hl9OHlcCnMaopu6CIm/BAaxXTQj6vou53owcWnJQutT0tzyX3t9aw0/RRbTIEa2dBoaM9vgXdTUd17XBK6ZItoWWgr/MwywGDjM6dPBMyWNNR0FTscpWD5+vnzCiOZEacMz3f9JAnWr9D+SiXO1BgfNN3gAWtyvzwXTS6TQZsItY1KWfKxOSd4kCG49ahfgDm9tH4Sa731iqCXNAWuALFLe4wfz4KntUltqGb9Ryrkpok68m0UCRtNsg90RLxNLF+PdFRH8Ngn3wbVeWh6uCs9jMTzc05AMqYSJX4Hw/ov4WwazQhn4Q7y8nndE1JZVOZ/IE0kKburwqD5NSxDE+AC1gkg7QqCmog3UBNQZiS9hPE8zd7NrMtBRG0BT9CyeVyek3xqxxlM5N3ww4WcXRN+IbqDYNtLBGW7tXXo=
  on:
    tags: true
